version: '2'
services:
    front:
        container_name: test_front
        build: ./docker
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www
        links:
            - mysql:mysql
        environment:
            - UID=1000
    mysql:
        container_name: test_mysql
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./docker/mysql/log:/var/log/mysql
    adminer:
        container_name: test_adminer
        build: ./docker/adminer/
        ports:
            - "4001:80"
